package ScannerPoint.example.ScannerPoint.customer.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;

import java.time.LocalDate;

@Entity
@Table(name = "vehicle")
public class Vehicle {

    /** Sri Lankan number plate, e.g. WP-CAV-9548 (same rule as chk_vehicle_reg). */
    public static final String PLATE_REGEX = "^(WP|CP|SP|NP|EP|NW|NC|UP|SG)-[A-Z]{2,3}-[0-9]{4}$";

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "vehicle_id")
    private Integer id;

    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "customer_id", nullable = false)
    private Customer customer;

    @Column(name = "registration_no", nullable = false, unique = true, length = 12)
    private String registrationNo;

    /** Generated by MySQL from the first two letters of the plate – read only. */
    @Column(name = "province_code", length = 2, insertable = false, updatable = false)
    private String provinceCode;

    @Column(nullable = false, length = 30)
    private String make;

    @Column(nullable = false, length = 30)
    private String model;

    @Column(name = "manufacture_year", nullable = false, columnDefinition = "smallint")
    private Integer manufactureYear;

    @Enumerated(EnumType.STRING)
    @Column(name = "fuel_type", nullable = false)
    private FuelType fuelType;

    @Column(name = "current_mileage", nullable = false)
    private Integer currentMileage = 0;

    @Column(name = "last_service_date")
    private LocalDate lastServiceDate;

    @Column(name = "last_service_mileage")
    private Integer lastServiceMileage;

    /** How vehicles are shown everywhere: "WP-CAV-9548 – Honda Vezel". */
    public String getDisplayName() {
        return registrationNo + " – " + make + " " + model;
    }

    public Integer getId() { return id; }
    public void setId(Integer id) { this.id = id; }
    public Customer getCustomer() { return customer; }
    public void setCustomer(Customer customer) { this.customer = customer; }
    public String getRegistrationNo() { return registrationNo; }
    public void setRegistrationNo(String registrationNo) { this.registrationNo = registrationNo; }
    public String getProvinceCode() { return provinceCode; }
    public String getMake() { return make; }
    public void setMake(String make) { this.make = make; }
    public String getModel() { return model; }
    public void setModel(String model) { this.model = model; }
    public Integer getManufactureYear() { return manufactureYear; }
    public void setManufactureYear(Integer manufactureYear) { this.manufactureYear = manufactureYear; }
    public FuelType getFuelType() { return fuelType; }
    public void setFuelType(FuelType fuelType) { this.fuelType = fuelType; }
    public Integer getCurrentMileage() { return currentMileage; }
    public void setCurrentMileage(Integer currentMileage) { this.currentMileage = currentMileage; }
    public LocalDate getLastServiceDate() { return lastServiceDate; }
    public void setLastServiceDate(LocalDate lastServiceDate) { this.lastServiceDate = lastServiceDate; }
    public Integer getLastServiceMileage() { return lastServiceMileage; }
    public void setLastServiceMileage(Integer lastServiceMileage) { this.lastServiceMileage = lastServiceMileage; }
}
